# Generated by Django 4.2.1 on 2023-06-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_param"),
    ]

    operations = [
        migrations.CreateModel(
            name="personal_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("age", models.ImageField(upload_to="")),
                ("gender", models.CharField(max_length=40)),
                ("comments", models.TextField()),
            ],
        ),
    ]
