# Generated by Django 4.2.2 on 2023-06-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("country_code", models.CharField(max_length=10)),
                ("user_name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=10)),
                ("gmail", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
