# Generated by Django 4.2.2 on 2023-07-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_user_delete_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="create_room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=20)),
                ("tag", models.CharField(max_length=20)),
                ("text", models.CharField(max_length=20)),
            ],
        ),
    ]
