# Generated by Django 4.2.2 on 2023-07-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_create_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="create_room",
            name="followers",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
