# Generated by Django 4.2.2 on 2023-07-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_create_room_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="create_room",
            name="room_ide",
            field=models.IntegerField(default=0),
        ),
    ]
