# Generated by Django 4.2.2 on 2023-07-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_create_room_room_ide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="create_room",
            name="room_ide",
            field=models.IntegerField(),
        ),
    ]
