# Generated by Django 4.2.1 on 2023-06-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_teacher_alter_email_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="student_name",
        ),
        migrations.AlterField(
            model_name="teacher",
            name="first_name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="last_name",
            field=models.CharField(max_length=40),
        ),
    ]
