# Generated by Django 4.2.1 on 2023-06-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="accounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=70)),
                ("user_email", models.CharField(max_length=100)),
                ("user_city", models.CharField(max_length=50)),
                ("user_education", models.CharField(max_length=50)),
                ("user_password", models.CharField(max_length=60)),
            ],
        ),
    ]
