# Generated by Django 4.2.1 on 2023-06-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_accounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="user_city",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="accounts",
            name="user_password",
            field=models.IntegerField(),
        ),
    ]
