# Generated by Django 4.2.1 on 2023-06-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_accounts_user_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="transcript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long_text", models.TextField()),
            ],
        ),
    ]
